// Generiert von scripts/build-icons.mjs — NICHT manuell editieren.
// Typdeklaration für icons/icons.js. Siehe icons/README.md „Verwendung“.

export interface CdsIconEntry {
  name: string;
  area: string;
  style: 'solid' | 'outline' | 'mixed';
  viewBox: string;
  strokeWidth?: string;
  /** Nur das innere Markup (für set:html in ein bestehendes <svg>). */
  body: string;
  /** Komplettes <svg>…</svg> (currentColor, self-contained). */
  svg: string;
  usage?: string[];
}

export const coBuilding: CdsIconEntry;
export const coMark: CdsIconEntry;
export const esWindowCheck: CdsIconEntry;
export const kiBot: CdsIconEntry;
export const uiAcademicCap: CdsIconEntry;
export const uiAdjustmentsHorizontal: CdsIconEntry;
export const uiArrowDownTray2: CdsIconEntry;
export const uiArrowDownTray: CdsIconEntry;
export const uiArrowPath: CdsIconEntry;
export const uiArrowTrendingUp: CdsIconEntry;
export const uiBanknotes: CdsIconEntry;
export const uiBars3CenterLeft: CdsIconEntry;
export const uiBars3: CdsIconEntry;
export const uiBolt2: CdsIconEntry;
export const uiBolt: CdsIconEntry;
export const uiBookOpen: CdsIconEntry;
export const uiBriefcase2: CdsIconEntry;
export const uiBriefcase: CdsIconEntry;
export const uiBuildingOffice: CdsIconEntry;
export const uiCalendarDays: CdsIconEntry;
export const uiCalendar: CdsIconEntry;
export const uiCaretDown: CdsIconEntry;
export const uiChartBar: CdsIconEntry;
export const uiChatBubbleLeftRight: CdsIconEntry;
export const uiChatBubbleOvalLeftEllipsis: CdsIconEntry;
export const uiChatBubbleOval: CdsIconEntry;
export const uiCheckBadge: CdsIconEntry;
export const uiCheckCircle2: CdsIconEntry;
export const uiCheckCircle: CdsIconEntry;
export const uiCheck: CdsIconEntry;
export const uiChevronDown: CdsIconEntry;
export const uiChevronUpDown: CdsIconEntry;
export const uiCircleStack: CdsIconEntry;
export const uiClock: CdsIconEntry;
export const uiCodeBracket2: CdsIconEntry;
export const uiCodeBracketSquare: CdsIconEntry;
export const uiCodeBracket: CdsIconEntry;
export const uiCog6tooth: CdsIconEntry;
export const uiCog: CdsIconEntry;
export const uiComputerDesktop: CdsIconEntry;
export const uiCpuChip2: CdsIconEntry;
export const uiCpuChip: CdsIconEntry;
export const uiCube2: CdsIconEntry;
export const uiCubeTransparent: CdsIconEntry;
export const uiCube: CdsIconEntry;
export const uiCurrencyEuro: CdsIconEntry;
export const uiCursorArrowRays: CdsIconEntry;
export const uiDevicePhoneMobile: CdsIconEntry;
export const uiDocumentText: CdsIconEntry;
export const uiFaceSmile: CdsIconEntry;
export const uiFlag: CdsIconEntry;
export const uiFolder: CdsIconEntry;
export const uiHandRaised: CdsIconEntry;
export const uiHeart: CdsIconEntry;
export const uiInformationCircle: CdsIconEntry;
export const uiLanguage: CdsIconEntry;
export const uiLink: CdsIconEntry;
export const uiListBullet: CdsIconEntry;
export const uiLockClosed2: CdsIconEntry;
export const uiLockClosed: CdsIconEntry;
export const uiMagnifyingGlass: CdsIconEntry;
export const uiMapPin2: CdsIconEntry;
export const uiMapPin: CdsIconEntry;
export const uiMegaphone: CdsIconEntry;
export const uiNewspaper2: CdsIconEntry;
export const uiNewspaper: CdsIconEntry;
export const uiPause: CdsIconEntry;
export const uiPencilSquare: CdsIconEntry;
export const uiPhoto: CdsIconEntry;
export const uiPlay: CdsIconEntry;
export const uiPuzzlePiece: CdsIconEntry;
export const uiQuote: CdsIconEntry;
export const uiRectangleStack: CdsIconEntry;
export const uiRocketLaunch: CdsIconEntry;
export const uiShieldCheck2: CdsIconEntry;
export const uiShieldCheck: CdsIconEntry;
export const uiSparkles2: CdsIconEntry;
export const uiSparkles3: CdsIconEntry;
export const uiSparkles4: CdsIconEntry;
export const uiSparkles: CdsIconEntry;
export const uiSquare2Stack: CdsIconEntry;
export const uiSquares2x2: CdsIconEntry;
export const uiSquaresPlus: CdsIconEntry;
export const uiStar2: CdsIconEntry;
export const uiStar: CdsIconEntry;
export const uiSun: CdsIconEntry;
export const uiSwatch: CdsIconEntry;
export const uiTableCells: CdsIconEntry;
export const uiTag: CdsIconEntry;
export const uiTrophy2: CdsIconEntry;
export const uiTrophy: CdsIconEntry;
export const uiUserGroup2: CdsIconEntry;
export const uiUserGroup: CdsIconEntry;
export const uiUsers2: CdsIconEntry;
export const uiUsers: CdsIconEntry;
export const uiViewfinderCircle: CdsIconEntry;
export const uiWindow: CdsIconEntry;
export const uiWrenchScrewdriver: CdsIconEntry;
export const woNetwork: CdsIconEntry;

export const icons: Record<string, CdsIconEntry>;
export default icons;
